const Discord = require('discord.js');
const makeEmbed = require('../functions/makeEmbed.js');     

// THIS DOESN'T DO ANYTHING YET

module.exports = (client, message, args) => {
	console.log(`Log: ${message.member.guild.nameAcronym}: safety: ${message.member.user.tag} is requesting safety information on <${args}>.`);
	
	if (args.length === 0) {
		makeEmbed.embed1Field(client, `10070709`, `**Safety Information Index**`, "To learn various things related to safety and dosage, just use one of the !safety commands below. For more dosage tools, summon the DoseBot command guide using ``--help``.\n\n``!safety basic\n!safety combinations\n!safety dosage\n!safety harmreduction\n!safety hppd\n!safety drugtesting\n!safety fentanyl\n!safety narcan\n!safety recovery\n!safety psilocybin\n!safety cannabinoids\n!safety benzodiazepines\n!safety dxm\n!safety mdma\n!safety mdma-supplements\n!safety microdosing``", message);
		return
	};

	if (args[0] === "basic") {
		makeEmbed.embed1Field(client, `10070709`, `**Basic Psychedelic Safety**`, "If you are planning to use psychedelic drugs for the first time, we strongly advise that you do some general reading about how to prepare for a safe and productive trip.\n\nBesides the actual chemical contents going into your body, the psychedelic is equally affected by one's surroundings and emotional experience. Set refers to personal preperation, including both one's personal history and their emotional state at the time of the trip. Setting refers to the physical surroundings: environments, sounds, other people, cultural icons, and anything else one perceives.\n\nIn order to prepare for a positive and productive trip, it is helpful to read about how people respond to different drugs under various circumstances, and try to intentionally construct a set and setting that feel comfortable and catered to you on the day of your trip. Here are some resources that provide helpful information on how to prepare yourself for a trip:\n\n__Bad Trip Guide__: https://web.archive.org/web/20160301093438/http://www.badtripguide.com:80/\n\n__How to Use Psychedelics__ http://howtousepsychedelics.org/\n\n__Session Games People Play: A Manual for the Use of LSD__ http://www.luminist.org/archives/session.htm\n\n__Handbook for the Therapeutic Use of LSD: Individual and Group Procedures__ http://www.maps.org/research-archive/ritesofpassage/lsdhandbook.pdf\n\nFor information on the individual substances you are consuming or may be considering consuming, be sure to also visit:\n\n__PsychonautWiki Substances Index__ https://psychonautwiki.org/wiki/Psychoactive_substance_index\n__Erowid Psychoactives Vault__\n\nhttps://www.erowid.org/psychoactives/psychoactives.shtml\n\n__Subjective Effect Index__ https://www.effectindex.com/", message);
		return
	};

	if (args[0] === "combinations") {
		makeEmbed.embedImg1Field(client, `10070709`, `**Drug Combinations**`, "If you are on any medication taken regularly, especially if you are taking antidepressants or other psychiatric drugs including lithium or MAOIs, be sure to spend time researching and known interactions with any psychedelics or empathogens you plan on taking. Search forum posts and read what others have experienced under similar chemical combinations.\n\nBe sure to check your Tripsit's drug interaction page, which contains the following chart of great utility, as well as futher information on interactions:\n\n[Tripsit Guide to Drug Combinations](https://wiki.tripsit.me/wiki/Drug_combinations) (last updated April 2016)\n\n[Hobbyist breakdown regarding the effects of SSRIs, MAOIs and RIMAs on serotonergic psychedelics:](https://www.reddit.com/r/DMT/comments/73zccm/an_in_depth_explanation_on_how_ssris_and_maois/)\n\nRelated studies:\n\n[Chronic Administration of Serotonergic Antidepressants Attenuates the Subjective Effects of LSD in Humans (1996)](http://psychonautdocs.com/docs/bonson_chronic.pdf)\n\n[Alterations in responses to LSD in humans associated with chronic administration of tricyclic antidepressants, monoamine oxidase inhibitors or lithium](https://www.sciencedirect.com/science/article/pii/0166432896001027) (1996)\n\nTripsit Combination Chart:", "https://i.imgur.com/yOXv1Yn.png", message);
		return
   };

    if (args[0] === "dosage") {
	makeEmbed.embed1Field(client, `10070709`, `**Dosage Information & Measurement Considerations**`, "It always helps to know the dosage and effect of chemicals before you take them. Always ask your source if they know the dosage drugs you acquire, and if possible ask others who have already tripped on it what their impressions were.\n\nIf you are taking a substance for the first time, start by taking a low dose to test its effects on your psyche and physiology before delving more deeply. Suggested dosages are available through the DoseBot command ``--info <substance>``.\n\nUnfortunately, we often end up with drugs of unknown or degraded quality, and without an effective means of testing their effects before taking them. If you do not know the dosage of your drug (but are sure of what substance it contains), test it by taking a small quantity of what appears to be a single intended dose.\n\nIf you are taking chemicals that come as a powder or crystal, buy a milligram scale. Do not attempt to approximate milligram quantities by eyeballing them.", message);
	return
};

	if (args[0] === "harmreduction") {
		 makeEmbed.embedImg1Field(client, `10070709`, `**Harm Reduction Basics**`, "Harm reduction information via Psychsitter and DanceSafe:\n\n__Trends in Harm Reduction interview with DanceSafe__ https://itunes.apple.com/us/podcast/psychedelic-salon/id1235694853?mt=2&i=1000390260729\n\n__The Manual of Psychedelic Support 2nd Edition is available for download online. http://psychsitter.com/download-manual/__\n\nThe [KnowDrugs app](https://knowdrugs.info/) shows the latest drug checking / pill testing results from around the world, provides information on substances, effects and interactions and offers counselling and advice regarding substances, drugs and addiction.\n\nSome illustrated advice from Zendo Project on how to be a good tripsitter/how to be present during a trip, for anyone looking for a quick lesson:", "https://i.imgur.com/gUaP18v.png", message);
		 return
	};

	if (args[0] === "testing") {
		makeEmbed.embedImg1Field(client, `10070709`, `**Harm Reduction Basics**`, "When ingesting mind-altering chemicals, it is critical to test their contents, especially if they were acquired from a new or unreliable source. This can be done simply using a reagent kit, available from the sources below:\n\n[DanceSafe (US)](https://dancesafe.org/shop/)\n[Fentanyl test strips](https://dancesafe.org/dancesafe-now-offering-fentanyl-testing-strips/)\n[Reagent-Tests (UK)](https://www.reagent-tests.uk/product/mdma-lsd-test/)\n[EZ Test (NL, worldwide shipping)](http://www.eztest.com/product-category/ez-test-kits/)\n[Lunar Laboratories](http://www.lunarlaboratories.com/) (international shipping)\n[Elevation Chemicals](https://elevationchemicals.com/)\n[TestKitPlus](https://testkitplus.com/) (CAN, ships to US)\n[SIN](https://shop.sin.org.pl/) (EU)\n[HUP](https://thehup.org/) (EU, worldwide shipping)\n\nBelow are some color identification charts for various reagent kits and chemicals of popular interest:\n\n[DanceSafe Reagent Test Identification Chart](https://i.imgur.com/lJvOZJt.png) (shown)\n[Drugs Forum Reagent Identifications](https://i.imgur.com/wWjT6a1.jpg)\n[Bunk Police reagent videos](https://www.youtube.com/user/BunkPolice/videos)\n[ReagentTesting subreddit color spectrum](https://www.reddit.com/r/ReagentTesting/wiki/color-spectrum)", "https://i.imgur.com/lJvOZJt.png", message);
		return
   };

   if (args[0] === "drugtesting") {
	makeEmbed.embedImg1Field(client, `10070709`, `**Harm Reduction Basics**`, "When ingesting mind-altering chemicals, it is critical to test their contents, especially if they were acquired from a new or unreliable source. This can be done simply using a reagent kit, available from the sources below:\n\n[DanceSafe (US)](https://dancesafe.org/shop/)\n[Fentanyl test strips](https://dancesafe.org/dancesafe-now-offering-fentanyl-testing-strips/)\n[Reagent-Tests (UK)](https://www.reagent-tests.uk/product/mdma-lsd-test/)\n[EZ Test (NL, worldwide shipping)](http://www.eztest.com/product-category/ez-test-kits/)\n[Lunar Laboratories](http://www.lunarlaboratories.com/) (international shipping)\n[Elevation Chemicals](https://elevationchemicals.com/)\n[TestKitPlus](https://testkitplus.com/) (CAN, ships to US)\n[SIN](https://shop.sin.org.pl/) (EU)\n[HUP](https://thehup.org/) (EU, worldwide shipping)\n\nBelow are some color identification charts for various reagent kits and chemicals of popular interest:\n\n[DanceSafe Reagent Test Identification Chart](https://i.imgur.com/lJvOZJt.png) (shown)\n[Drugs Forum Reagent Identifications](https://i.imgur.com/wWjT6a1.jpg)\n[Bunk Police reagent videos](https://www.youtube.com/user/BunkPolice/videos)\n[ReagentTesting subreddit color spectrum](https://www.reddit.com/r/ReagentTesting/wiki/color-spectrum)", "https://i.imgur.com/lJvOZJt.png", message);
	return
};

	if (args[0] === "hppd") {
		makeEmbed.embed1Field(client, `10070709`, `**Psychedelic-Induced HPPD and PTSD**`, "The intense mental effects of psychedelics can bring on a set of symptoms known as Hallucinogen Persisting Perceptual Disorder (HPPD), and overwhelming psychedelic experiences can also induce Post-Traumatic Stress Disorder (PTSD); it is not unusual for these conditions to occur in tandem.\n\nHPPD can be recognized by persistent visual distortions while sober including visual static, increased tracers or afterimages, confusion over color perception or identification, bright or dark halos around objects of visual focus, size and perspective distortion, and many other features.\n\nPTSD may emerge from traumatizing or unintegrated experiences had under the influence of psychedelics. These experiences may also be tied up in HPPD perceptions, which can make life very uncomfortable.\n\nMost sufferrers of HPPD find it subsides within a few months of abstinence from psychedelics. For more information on managing these symptoms, refer to the following:\n\n[Erowid HPPD FAQ](https://erowid.org/psychoactives/health/hppd/hppd_faq.shtml)\n[HPPD Online Forum](http://hppdonline.com/)\n[/r/HPPD/](https://www.reddit.com/r/HPPD/)\n\nIf you are overwhelmed by past psychedelic experience or suspect you may be developing symptoms of PTSD as a result of them, refer to MAPS's Integration List of therapists who practice psychedelic integration:\n\n[MAPS Psychedelic Integration List](http://www.maps.org/resources/psychedelic-integration-list)", message)
		return
   };

   if (args[0] === "ptsd") {
	makeEmbed.embed1Field(client, `10070709`, `**Psychedelic-Induced HPPD and PTSD**`, "The intense mental effects of psychedelics can bring on a set of symptoms known as Hallucinogen Persisting Perceptual Disorder (HPPD), and overwhelming psychedelic experiences can also induce Post-Traumatic Stress Disorder (PTSD); it is not unusual for these conditions to occur in tandem.\n\nHPPD can be recognized by persistent visual distortions while sober including visual static, increased tracers or afterimages, confusion over color perception or identification, bright or dark halos around objects of visual focus, size and perspective distortion, and many other features.\n\nPTSD may emerge from traumatizing or unintegrated experiences had under the influence of psychedelics. These experiences may also be tied up in HPPD perceptions, which can make life very uncomfortable.\n\nMost sufferrers of HPPD find it subsides within a few months of abstinence from psychedelics. For more information on managing these symptoms, refer to the following:\n\n[Erowid HPPD FAQ](https://erowid.org/psychoactives/health/hppd/hppd_faq.shtml)\n[HPPD Online Forum](http://hppdonline.com/)\n[/r/HPPD/](https://www.reddit.com/r/HPPD/)\n\nIf you are overwhelmed by past psychedelic experience or suspect you may be developing symptoms of PTSD as a result of them, refer to MAPS's Integration List of therapists who practice psychedelic integration:\n\n[MAPS Psychedelic Integration List](http://www.maps.org/resources/psychedelic-integration-list)", message)
	return
};

    if (args[0] === "narcan") {
	makeEmbed.embedImg1Field(client, `10070709`, `**Obtaining Narcan**`, "Narcan, a nasal spray which counteracts the effects of opioid overdose, is available without a prescription in most US states. Like an Epipen, carrying Narcan can help prepare you for the worst-case scenario. For a two-dose package, Narcan costs between $40-$150 depending on where it is available, and may be covered by insurance.\n\n[General information and Walgreens/CVS distribution](https://evolutionstreatment.com/states-offer-naloxone-over-the-counter/)\n\n[Additional CVS availability](https://www.cvs.com/content/prescription-drug-abuse/save-a-life)\n\n[Retail pricing information](https://www.goodrx.com/narcan)", "http://static-41.sinclairstoryline.com/resources/media/1ebc476d-0d0b-484e-992d-17e58365a56b-large16x9_1280x960_71025P00QKAPY.jpg", message);
	return
};

if (args[0] === "mdma") {
	makeEmbed.embed3Field(client, `10070709`, "MDMA Identification", "Due to being one of the most adulterated drugs, the impurity of MDMA in different regions and at different times varies. According to data collected from a range of sources, anywhere between 30% and 60% of what is being sold as molly or ecstasy in the USA is not in fact MDMA. While MDMA purity is generally higher in Europe, adulterants do still appear. Substances such as synthetic cathinones (methylone, butylone, MDPV, ethylone, etc.), ketamine, amphetamine, methamphetamine, PMA or PMMA, alpha-Pyrrolidinovalerophenone (known as flakka), DXM, and even heroin or fentanyl have been found in supposed MDMA pills. There are also less controversial ingredients such as aspirin and caffeine, as well as inert binding agents.\n\nVisit [Ecstacy Data](https://www.ecstasydata.org/) for lab tests and [Pill Reports](https://www.pillreports.net/) for subjective user reports.", "MDMA Harm Reduction", "MDMA can raise body temperature. It is important to take frequent breaks from physical activity to cool off.\n\nAnother issue is water retention and the associated decreased salinity of the blood. During the roll, you may notice that you have difficulty peeing or experience cranial pressure. You may feel thirsty and dry-mouthed, and it is important to stay hydrated, but drink no more than 1-2 glasses of water per hour. Drinking beverages with electrolytes or isotonic (salty) fluids will reduce the risk of hyponatremia. Drinking alcohol is not recommended as it dehydrates you, depletes electrolytes, dulls the stimulating effects of the MDMA, and can increase the risk of blackouts & hangovers. To determine if you are dehydrated, refer to the [urine color chart here](https://imgur.com/a/3UrQfwk).", "Supplements", "For more information on supplements that can be taken to increase the comfort and safety of your MDMA trip, type ``!safety mdma-supplements``", message);
	return
};

if (args[0] === "mdma-supplements") {
	makeEmbed.embed3Field(client, `10070709`, "MDMA Supplements", "Magnesium is often taken to reduce jaw clenching gurning and reduce nausea. There are a variety of types of magnesium with different degrees of bioavailability, with glycinate/chelate as the most recommended. Antacids and natural remedies such as ginger may also be taken to reduce nausea. Many users suggest pre-loading and post-loading with neuroprotective antioxidant supplements such as Alpha Lipoic Acid (ALA), Acetyl-L-carnitine (ALCAR), Ascorbate (Vitamin C), Vitamin E, Nicotinamide, Ubiquinone (Co-Q10), grape seed extract, and green tea extract (EGCG). It is also recommended to take 5-HTP (with vitamin B6) and EGCG to help promote the replacement of endogenous serotonin after a roll. More information can be found at:\n\n[PsychedSubstance's MDMA Comedown Guide](https://www.youtube.com/watch?v=FlMxTpONKT0)\n[RollSafe](https://rollsafe.org/)\n[DanceSafe](https://dancesafe.org/ecstasy/)\n\nAs seen in the tripsit.me drug combinations chart, cannabis has a low risk and high synergy with MDMA, but anecdotal reports suggest increased headspace at higher doses, and caution should be used considering the tendency of other substances to be sold as MDMA.", "Risky Combinations", "MAOIs should not be taken with MDMA, due to the increased risk of the [potentially fatal serotonin syndrome](http://www.mayoclinic.org/diseases-conditions/serotonin-syndrome/symptoms-causes/dxc-20305673). SSRIs will typically reduce the effects of MDMA, SNRIs may change effects, and TCAs will generally increase the effects at unknown levels. Some users report utilizing SSRIs after a roll to [stop the flood of serotonin and reduce neurotoxicity](https://www.erowid.org/chemicals/mdma/mdma_info9.shtml).\n\nMDMA also lowers the seizure threshold so proceed with extreme caution if you have a history of seizures.", "Other", "Studies have shown that MDMA interferes with one's ability to discern negative emotion from facial expression. While fear reduction is great for therapy and having a good time, take care in unfamiliar places and with strangers.", message);
	return
};


if (args[0] === "psilocybin") {
	makeEmbed.embedImg1Field(client, `10070709`, `**Psilocybin Dosage & Potency**`, `Different mushroom species can vary in potency. Even among the same species, actual psilocybin content may vary. For more information visit [The Shroomery](http://www.shroomery.org/).\n\n[Multi Species Psilocybin Mushroom Dosage Calculator](https://www.psychedelicsdaily.com/psilocybin/multi-species-psilocybin-mushroom-dosage-calculator/)\n\nBased on the Baseline-Cubensis algorithm developed by Hash C. Borgir using psilocybin concentration data from Paul Stamets, this calculator can be used to determine dosages for various species of psilocybin mushrooms.`, `https://i.imgur.com/Dr6lvrQ.jpg`, message);
	return
};

if (args[0] === "cannabinoids") {
	makeEmbed.embedImg3Field(client, `10070709`, "Cannabinoid Profiles", "Information regarding various parts of the cannabis plant continues to grow. As you may be aware, CBD has little to no psychoactive component and can be used to treat pain and anxiety. Other calming cannabinoids are CBN and CBG. THCV is energetic and shows promise as an appetite suppressant. Below are a variety of uses of different cannabinoids, which unfortunately remain unevaluated by drug regulating agencies due to a prohibition on research.\n\n[Cannabinoid effects chart 1](https://i.imgur.com/bblfuUR.jpg)\n[Cannabinoid effects chart 2](https://i.imgur.com/eZe4E0z.jpg)\n[Cannabinoid effects by strain](https://i.imgur.com/MtqQoF2.png)\n[Additional infographics](https://cosmosmagazine.com/biology/infographic-how-cannabis-works)\n\nFor more information on cannabinoid levels, check out [Leafly's strain explorer](https://www.leafly.com/explore) which has information on many strains of cannabis.", "Smoked Cannabis vs. Edibles", "\"The base pharma- cokinetic equivalency ratio is 1 to 5.71. This means that one milligram of THC in edible form, is equivalent to 5.71 milligrams of THC in smokable form.\" ([Source](https://www.colorado.gov/pacific/sites/default/files/MED%20Equivalency_Final%2008102015.pdf))", "Cannabinoid Vaporization Temperatures", "Below are shown are the effects and vaporization temperatures of major cannabinoids and other compounds found in cannabis, sourced from Leafly a [2001 study McPartland & Russo](https://www.cannabis-med.org/data/pdf/2001-03-04-7.pdf)", "https://i.imgur.com/2tljnsK.png", message);
	return
};

if (args[0] === "benzodiazepines") {
	makeEmbed.embed1Field(client, `10070709`, "Benzodiazepine Converter", "This is a simple calculator made to help you figure out how much a given benzodiazepine converts to another benzodiazepine dosage.\n\n[Benzo converter at Tripsit](http://benzo.tripsit.me/).", message);
	return
};

if (args[0] === "benzos") {
	makeEmbed.embed1Field(client, `10070709`, "Benzodiazepine Converter", "This is a simple calculator made to help you figure out how much a given benzodiazepine converts to another benzodiazepine dosage.\n\n[Benzo converter at Tripsit](http://benzo.tripsit.me/)", message);
	return
};

if (args[0] === "dxm") {
	makeEmbed.embed1Field(client, `10070709`, "DXM Dosage Calculator", "These web tools take your weight and suggest appropriate dosages for the different \"plateaus\" of DXM.\n\n[DXM Calculator at Tripsit](http://dxm.tripsit.me/)\n[DXMcalc](http://dexcalc.com/)\n\nA DXM calculator is also available through DoseBot via the command ``--dxmcalc <weight>``.", message);
	return
};

if (args[0] === "recovery") {
	makeEmbed.embedImg1Field(client, `10070709`, `**Recovery Position**`, `Until help arrives, place your friend in the shown position.`, "https://i.imgur.com/5KYeee0.jpg", message);
	return;
}

if (args[0] === "fentanyl") {
	makeEmbed.embed1Field(client, `10070709`, `**Fentanyl**`, "The powerful synthetic opioid fentanyl has contaminated the overall drug supply, leading to the deadly poisoning of many users of heroin, cocaine, pressed pills, and other substances. Fentanyl and its analogues (acetyl-fentanyl, furanyl-fentanyl, carfentanil, etc.) are not known for their euphoria, but rather their incredibly small size, making them easy for drug traffickers to transport.\n\nMost street level dealers and users are unaware of fentanyl's presence in the substances they sell and consume. However, respondents in a recent study said that knowing their drugs contained fentanyl would lead them to modify their behavior by not using, using slowly, using in situations where naloxone is available, or changing their buying habits.\n\nAs such, testing substances for the presence of fentanyl is suggested practice. Perhaps counterintuitively, the substance should be thoroughly mixed before testing, as fentanyl is never distributed evenly, with sometimes fatal doses sitting on one side of a bag or edge of a tablet (the 'chocolate chip cookie effect'). When testing, pay special attention to the fact that methamphetamine and MDMA can trigger false positives if too much of the substance is tested; dilute the sample with water.\n\nFollow the testing kit instructions closely based on whether your sample is liquid or powder. A result of one line is positive: the sample contains fentanyl. A result of two lines is negative: the sample does not contain fentanyl. A negative result does not mean a substance is safe to consume or that an overdose is not a possibility, as not all test strips can detect all analogues and other risk factors may exist.\n\nAdditional information can be found at [DanceSafe](https://dancesafe.org/product/fentanyl-test-strips-pack-of-10/) and [Harm Reduction Coalition](https://harmreduction.org/issues/fentanyl/).", message);
	return;
};

if (args[0] === "microdosing") {
	makeEmbed.embed1Field(client, `10070709`, "Microdosing Information", "A variety of resources on microdosing LSD and mushrooms, including a paid course and access to a private community, are available at [Third Wave](https://thethirdwave.co/).\n\nParticipants in the [Fadiman/Korb microdosing study](https://sites.google.com/view/microdosingpsychedelics/home), using LSD, 1p-LSD, or mushrooms, have reported using certain medications and supplements with no adverse response. If you are looking for a medication or supplement of interest, we recommend using CTRL+F to [find it in their study data](https://sites.google.com/view/microdosingpsychedelics/drugs-and-supplements).\n\nDr. Dave Nichols talks about the potential downsides of microdosing, including cardiac valvulopathy, on [this Psychedelic Salon podcast](https://psychedelicsalon.com/salon2-034-psychedelic-chemistry/). Concern arises from activity with the 5HT-2B receptor as indicated in the 2011 research paper [Serotonin Receptors and Heart Valve Disease – it was meant 2B](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3179857/pdf/nihms322884.pdf).", message);
	return
}
	else {
		message.channel.send("Sorry, I don't know that one. Try ``!safety`` for a list of available topics.");
		return
	}
}
